<a href="https://colab.research.google.com/github/LeandroDeFRusso/API-Node.js--Leandro-de-F.-Russo/blob/main/Pr%C3%A1ticas_com_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
#1

array = np.zeros(10)

print(array)

print(array.dtype)
print(array.shape)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


In [3]:
#2

array = np.ones(10)

array_float = array.astype(np.float64)

print(array)
print(array_float)
print(array_float.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64


In [4]:
#3

array = np.arange(0, 10)

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#4

array = np.reshape(np.arange(0, 9), (3, 3))

print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#5

valores = np.array([1, 2, 0, 0, 4, 0])
indice = np.nonzero(valores)

print(indice)

(array([0, 1, 4]),)


In [7]:
#6

array = np.linspace(0, 1, 12)

print(array)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [8]:
#7

identidade = np.eye(5)

print(identidade)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
#8

aleatorios = np.random.default_rng(42)
array = aleatorios.random((3, 3, 3))

print(array)

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


In [10]:
#9

aleatorios = np.random.default_rng(42)
matriz = aleatorios.random((10, 10))

print("O mínimo desta matriz é:", matriz.min())
print("O máximo desta matriz é:", matriz.max())

O mínimo desta matriz é: 0.007362269751005512
O máximo desta matriz é: 0.9756223516367559


In [11]:
#10

valor = np.array([1, 2, 3, 4, 5], dtype=float)

valor_normalizado = (valor - valor.mean()) / valor.std()

print(valor_normalizado)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [12]:
#11

array = np.array([1, 2, 3], dtype=np.int32)

array_float_32 = array.astype(np.float32)
array_i64 = array_float_32.astype(np.int64)

print(array.dtype, array_float_32.dtype, array_i64.dtype)

int32 float32 int64


In [13]:
#12

limite = np.array([2, 5, 7, 1, 9])
limite_clipped = np.clip(limite, 0, 5)

print(limite_clipped)

[2 5 5 1 5]


In [14]:
#13

valor = np.arange(10)
valor_invertido = np.flip(valor)

print(valor_invertido)

[9 8 7 6 5 4 3 2 1 0]


In [15]:
#14

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h = np.hstack((a, b))
v = np.vstack((a, b))

print("A horizontal é:", h)
print("A vertical é:\n", v)

A horizontal é: [1 2 3 4 5 6]
A vertical é:
 [[1 2 3]
 [4 5 6]]


In [16]:
#15

matriz = np.diag(np.full(4, 5))

print(matriz)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


In [17]:
#16

Matriz = np.arange(12).reshape(3, 4)

total_linhas = Matriz.sum(axis=1)
total_colunas = Matriz.sum(axis=0)

print("O total de linhas é:", total_linhas)
print("O total de colunas é:", total_colunas)

O total de linhas é: [ 6 22 38]
O total de colunas é: [12 15 18 21]


In [18]:
#17

aleatorios = np.random.default_rng(42)
valores = aleatorios.integers(0, 10, size=100)

frequencias = np.bincount(valores, minlength=10)

print("As frequências são:", frequencias)

As frequências são: [ 9  9  6  9 15  7 11 15 12  7]


In [19]:
#18

valor = np.arange(20)
resultado = valor[1::3]

print(resultado)

[ 1  4  7 10 13 16 19]


In [20]:
#19

valor = np.arange(20)
mascara_booleana = (valor % 2 == 0)
pares = valor[mascara_booleana]

print("A máscara é:", mascara_booleana)
print("Os pares são:", pares)

A máscara é: [ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
Os pares são: [ 0  2  4  6  8 10 12 14 16 18]


In [21]:
#20

lista = [[1, 2, 3], [4, 5, 6]]
Matriz = np.array(lista)

print("O array é:\n", Matriz)
print("O shape é:", Matriz.shape)
print("O dtype é:", Matriz.dtype)

O array é:
 [[1 2 3]
 [4 5 6]]
O shape é: (2, 3)
O dtype é: int64


In [22]:
#21

datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')

print(datas)

['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


In [23]:
#22

Matriz = np.array([[1., 2., 3.], [4., 5., 6.]])

Matriz_centralizada = Matriz - Matriz.mean(axis=0)

print(Matriz_centralizada)

[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


In [24]:
#23

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

elementwise = a * b
escalar = np.dot(a, b)

print("O produto elemento-a-elemento é:", elementwise)
print("O produto escalar é:", escalar)

O produto elemento-a-elemento é: [ 4 10 18]
O produto escalar é: 32


In [25]:
#24

Matriz = np.arange(12).reshape(3, 4)

Matriz[:, [0, 2]] = Matriz[:, [2, 0]]

print(Matriz)

[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


In [26]:
#25

a = np.array([[1, 2], [3, 4]])
b_flat = a.flatten()
b_ravel = a.ravel()
b_ravel[0] = 99
print(a)
print("\n", b_flat)

[[99  2]
 [ 3  4]]

 [1 2 3 4]


In [27]:
#26

tabuleiro = np.indices((8, 8)).sum(axis=0) % 2

print(tabuleiro)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
#27

valor = np.arange(-5, 6)
resultado = np.where(valor < 0, 0, valor)

print(resultado)

[0 0 0 0 0 0 1 2 3 4 5]


In [29]:
#28

rng = np.random.default_rng(0)
data = rng.random(1_000_000)
mean = data.mean()
error = abs(mean - 0.5)
print("Média:", mean, "Erro absoluto:", error)

Média: 0.5001592564636843 Erro absoluto: 0.00015925646368430968


In [30]:
#29

a = np.array([1, 2, 3])[:, None]
b = np.array([10, 20, 30, 40])

somas = a + b

print(somas)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [31]:
#30
from numpy.lib.stride_tricks import sliding_window_view

s = np.array([1, 2, 3, 4, 5])
k = np.array([1, 0, -1])
sw = sliding_window_view(s, k.size)
conv_valid = np.sum(sw * np.flip(k), axis=1)
print("Convolução (valid):", conv_valid)

Convolução (valid): [2 2 2]


In [32]:
#31

A = rng.normal(size=(5,4))
A_min = A.min(axis=0)
A_max = A.max(axis=0)
range_ = np.where(A_max != A_min, A_max - A_min, 1)
A_norm = (A - A_min) / range_
print("Original:\n", A)
print("Normalizado:\n", A_norm)

Original:
 [[ 1.49094907  0.94435386 -0.02251395 -0.13571596]
 [-0.95963055 -0.02685518  1.11267343  0.89208528]
 [ 0.52179943 -0.96786357  0.69747152 -1.57055269]
 [-0.4979807   0.66268666 -1.2872589  -0.4442346 ]
 [ 0.4030978  -0.88356851 -0.67175858  0.08502541]]
Normalizado:
 [[1.         1.         0.52699192 0.58264217]
 [0.         0.49210324 1.         1.        ]
 [0.60452228 0.         0.82699433 0.        ]
 [0.18838394 0.85270127 0.         0.45736243]
 [0.5560841  0.04408236 0.2564657  0.67227831]]


In [33]:
#32

Matriz = np.array([[3, 9], [1, 4], [2, 5]])

Matriz_ordenada = Matriz[Matriz[:, 1].argsort()]

print(Matriz_ordenada)

[[1 4]
 [2 5]
 [3 9]]


In [34]:
#33

x = np.array([3,1,2,3,2,3,1])
uniq, first_idx, counts = np.unique(x, return_index=True, return_counts=True)
print("Únicos:", uniq)
print("Primeira ocorrência:", first_idx)
print("Contagens:", counts)

Únicos: [1 2 3]
Primeira ocorrência: [1 2 0]
Contagens: [2 2 3]


In [35]:
#34

P = np.array([[0,0],[3,4],[6,8]])
diff = P[:, None, :] - P[None, :, :]
dist = np.sqrt(np.sum(diff**2, axis=-1))
print(dist)

[[ 0.  5. 10.]
 [ 5.  0.  5.]
 [10.  5.  0.]]


In [36]:
#35

aleatorios = np.random.default_rng(42)
Aleatorio = aleatorios.standard_normal((1000, 3))

covariancia = np.cov(Aleatorio, rowvar=False)
correlacao = np.corrcoef(Aleatorio, rowvar=False)

print("A covariância é:\n", covariancia)
print("A correlação é:\n", correlacao)

A covariância é:
 [[ 1.02807939  0.003405   -0.03028368]
 [ 0.003405    0.99691425  0.06347086]
 [-0.03028368  0.06347086  1.0227042 ]]
A correlação é:
 [[ 1.          0.00336338 -0.02953387]
 [ 0.00336338  1.          0.06285943]
 [-0.02953387  0.06285943  1.        ]]


In [37]:
#36

y = np.array([2, 0, 1, 2])
numero_classes = y.max() + 1

onehot = np.eye(numero_classes)[y]

print(onehot)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
#37

In [39]:
#38

In [40]:
#39

In [41]:
#40

In [42]:
#41

In [43]:
#42